apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  CRATER_ATOMFEED_DB_HOST: "{{ .Values.config.CRATER_ATOMFEED_DB_HOST }}"
  OPENMRS_HOST: "{{ .Values.config.OPENMRS_HOST }}"
  CRATER_URLT:  "{{ .Values.config.CRATER_URL }}"
  CRATER_ATOMFEED_DB_NAME:  "{{ .Values.config.CRATER_ATOMFEED_DB_NAME }}"
  OPENMRS_PORT: "{{ .Values.config.OPENMRS_PORT }}"
  