apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  OPENMRS_ATOMFEED_USER:  {{ .Values.secrets.OPENMRS_ATOMFEED_USER | b64enc | quote }}
  OPENMRS_ATOMFEED_PASSWORD:  {{ .Values.secrets.OPENMRS_ATOMFEED_PASSWORD| b64enc | quote }}
  CRATER_USERNAME:  {{ .Values.secrets.CRATER_USERNAME | b64enc | quote }}
  CRATER_PASSWORD:  {{ .Values.secrets.CRATER_PASSWORD | b64enc | quote }}
  CRATER_ATOMFEED_DB_USERNAME:  {{ .Values.secrets.CRATER_ATOMFEED_DB_USERNAME | b64enc | quote }}
  CRATER_ATOMFEED_DB_PASSWORD:  {{ .Values.secrets.CRATER_ATOMFEED_DB_PASSWORD | b64enc | quote }}
