apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: {{ .Chart.Name }}-nginx
    environment: {{ .Values.metadata.labels.environment }}

spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: 80
      name: '80'
  selector:
    app: {{ .Chart.Name }}-nginx
    environment: {{ .Values.metadata.labels.environment }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-php
  labels:
    app: {{ .Chart.Name }}-php
    environment: {{ .Values.metadata.labels.environment }}

spec:
  type: {{ .Values.service.php.type }}
  ports:
    - port: {{ .Values.service.php.port }}
      targetPort: 9000
      name: '9000'
  selector:
    app: {{ .Chart.Name }}-php
    environment: {{ .Values.metadata.labels.environment }}
