name: Build and Publish crater-atomfeed
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'workflow-issue'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'

jobs:
  build-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
     HELM_CHART_PATH: package/helm
    steps:
      - uses: actions/checkout@v2
      - name: Set env.ARTIFACT_VERSION version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
      - name: Package war
        run: mvn --no-transfer-progress clean package -DskipTests
      