name: Build and Publish
on:
  push:
    branches: [BAH-1938]
    paths-ignore:
      - "**.md"

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify app version
        run: |
          APP_VERSION=$(cat package/.appversion)
          if [ $(git tag -l "$APP_VERSION") ]; then 
            echo "App version $APP_VERSION already released. Please update app version in package/.appversion to represent next major/minor/patch increment"
            exit 1
          else
            echo "setting artifact version to $(echo $APP_VERSION-${{github.run_number}})"
            echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
          fi
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
      - name: Package
        run: mvn --no-transfer-progress clean package -DskipTests
      - name: Download bahmni-embedded-tomcat.zip
        run: sh .github/download_artifact.sh bahmni-package bahmni-embedded-tomcat ${{secrets.BAHMNI_PAT}}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/crater-atomfeed:${{env.ARTIFACT_VERSION}},bahmni/crater-atomfeed:latest
          