name: Build and Publish crater-atomfeed
on:
  push:
    branches:
      - main
      - 'release-*'
      - BAH-1938
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
  repository_dispatch:
    types: ['bahmni-embedded-tomcat-trigger']

jobs:
  build:
    name: Build crater-atomfeed war
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
      - name: Package war
        run: mvn --no-transfer-progress clean package -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: crater-atomfeed.war
          path: feed-integration-webapp/target/crater-atomfeed.war


  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Verify app version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Download bahmni-embedded-tomcat.zip
        run: sh .github/download_artifact.sh bahmni-package bahmni-embedded-tomcat ${{secrets.BAHMNI_PAT}}
      - uses: actions/download-artifact@v3
        with:
          name: crater-atomfeed.war
          path: feed-integration-webapp/target/
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/crater-atomfeed:${{env.ARTIFACT_VERSION}},bahmni/crater-atomfeed:latest
